name: persistence_y
description: "Abstract persistence API for Project Y."
version: 0.1.0
repository: https://github.com/Yogi-7y/Project-Y.git
homepage: https://github.com/Yogi-7y/Project-Y/tree/main/packages/persistence_y

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  meta: ^1.12.0

dev_dependencies:
  lints_y: ^0.1.0
  test: ^1.25.2
