name: persistence_y_shared_preferences
description: "SharedPreferences implementation for persistence_y."
version: 0.1.0
repository: https://github.com/Yogi-7y/Project-Y.git
homepage: https://github.com/Yogi-7y/Project-Y/tree/main/packages/persistence_y_shared_preferences

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  meta: ^1.12.0
  persistence_y:
    path: ../persistence_y
  shared_preferences: ^2.2.2

dev_dependencies:
  lints_y: ^0.1.0
  mocktail: ^1.0.4
  test: ^1.25.2
